# Generated by Django 4.1.5 on 2023-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_review', '0002_literaturereviewmember_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='papers_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the papers were last updated. Includes updating by search or documents upload.', null=True),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='ready_for_screening',
            field=models.BooleanField(default=False, help_text='If True, than papers were distributed between reviewers for screening.'),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='search_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the search was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='literaturereview',
            name='papers',
            field=models.JSONField(help_text='All papers in the literature review.', null=True),
        ),
    ]
