# Generated by Django 4.1.5 on 2023-01-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature_review', '0003_literaturereview_papers_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaturereview',
            name='min_decisions',
        ),
    ]
