# Generated by Django 4.1.5 on 2023-01-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature_review', '0005_alter_literaturereview_ready_for_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literaturereview',
            name='exclusion_criteria',
        ),
        migrations.RemoveField(
            model_name='literaturereview',
            name='inclusion_criteria',
        ),
    ]
