# Generated by Django 4.1.5 on 2023-01-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_review', '0006_remove_literaturereview_exclusion_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='review_type',
            field=models.CharField(choices=[('RE', 'Literature Review'), ('AN', 'Annotation Task')], default='AN', max_length=2),
        ),
    ]
