# Generated by Django 4.0.4 on 2022-10-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_alter_organisation_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisationmember",
            old_name="user",
            new_name="member",
        ),
    ]
