# Generated by Django 4.0.4 on 2022-09-10 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inclusion_criteria",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Inclusion Criteria",
                        null=True,
                        verbose_name="inclusion criteria",
                    ),
                ),
                (
                    "exclusion_criteria",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Exclusion Criteria",
                        null=True,
                        verbose_name="exclusion criteria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiteratureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Literature review name must be between 3 and 100 long.",
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Project description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "first_screening",
                    models.ForeignKey(
                        help_text="Citation screening ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_abstract_screening",
                        to="citation_screening.citationscreening",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiteratureReviewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "literature_review",
                    models.ForeignKey(
                        help_text="Literature Review ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citation_screening.literaturereview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
