# Generated by Django 4.0.4 on 2022-09-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citation_screening", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literaturereview",
            name="first_screening",
            field=models.ForeignKey(
                help_text="Citation screening ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_abstract_screening",
                to="citation_screening.citationscreening",
            ),
        ),
    ]
