# Generated by Django 4.0.4 on 2022-09-11 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citation_screening", "0002_alter_literaturereview_first_screening"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereview",
            name="exclusion_criteria",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="literaturereview",
            name="inclusion_criteria",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="literaturereview",
            name="papers",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="literaturereview",
            name="search_queries",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250),
                null=True,
                size=None,
            ),
        ),
    ]
