# Generated by Django 4.0.4 on 2022-09-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citation_screening", "0003_literaturereview_exclusion_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literaturereview",
            name="exclusion_criteria",
        ),
        migrations.RemoveField(
            model_name="literaturereview",
            name="inclusion_criteria",
        ),
        migrations.RemoveField(
            model_name="literaturereview",
            name="search_queries",
        ),
    ]
