# Generated by Django 4.0.4 on 2022-09-11 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_user_allow_logging_user_preferred_taxonomies"),
        ("citation_screening", "0005_literaturereview_exclusion_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literaturereviewmember",
            name="user",
        ),
        migrations.AddField(
            model_name="literaturereview",
            name="members",
            field=models.ManyToManyField(
                through="citation_screening.LiteratureReviewMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="literaturereviewmember",
            name="member",
            field=models.ForeignKey(
                default=None,
                help_text="User ID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="literaturereviewmember",
            name="role",
            field=models.CharField(
                choices=[("AD", "Admin"), ("ME", "Member")], default="ME", max_length=2
            ),
        ),
    ]
