# Generated by Django 4.0.4 on 2022-10-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_rename_user_organisationmember_member"),
        ("citation_screening", "0009_literaturereview_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereview",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisation",
                to="organisations.organisation",
            ),
        ),
    ]
