# Generated by Django 4.1.5 on 2023-01-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citation_screening", "0013_remove_literaturereview_discipline_and_more"),
        ("literature_review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationscreening",
            name="literature_review",
            field=models.ForeignKey(
                help_text="Literature Review ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="literature_review.literaturereview",
            ),
        ),
        migrations.DeleteModel(
            name="LiteratureReview",
        ),
        migrations.DeleteModel(
            name="LiteratureReviewMember",
        ),
    ]
