# Generated by Django 4.1.5 on 2023-01-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation_screening', '0015_citationscreening_tasks_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationscreening',
            name='distributed_papers',
            field=models.JSONField(help_text='List of papers which were already distributed amoung reviewers.', null=True),
        ),
    ]
