# Generated by Django 4.1.5 on 2023-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation_screening', '0016_citationscreening_distributed_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationscreening',
            name='distributed_papers',
            field=models.JSONField(help_text='List of papers which were already distributed among reviewers.', null=True),
        ),
    ]
